FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
    openssh-server \
    vim \
    net-tools \
    iputils-ping \
    curl \
    python3 \
    python3-pip

RUN mkdir /var/run/sshd
RUN echo 'root:21521955' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Cài đặt các thư viện Python
RUN pip3 install numpy matplotlib scikit-learn tensorflow keras opencv-python-headless jupyter netifaces

#RUN mkdir /VisualPhish
#COPY ./VisualPhish /VisualPhish

RUN mkdir /app
COPY ./agent_listener.py /app
COPY ./agent_train.py /app
COPY ./send_ckks_key.py /app/send_ckks_key.py
COPY ./get_ckks_key.py /app/get_ckks_key.py

RUN chmod +x /app/send_ckks_key.py
RUN chmod +x /app/get_ckks_key.py

WORKDIR /app

EXPOSE 5000 12345 22 8888

RUN pip3 install tenseal

CMD ["/usr/sbin/sshd", "-D"]
CMD ["sh", "-c", "python3 /app/agent_listener.py"]
